version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strap_api
    hostname: blog_strap_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
volumes:
  db: {}
